# Generated by Django 5.1.2 on 2024-11-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
