# Generated by Django 5.1.2 on 2024-11-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulators', '0002_alter_damage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulator',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
